= Título do documento

Primeira sentência do documento.
= Título do Documento
Nome Sobrenome <nome.sobrenome@learnxinyminutes.com>

Início do documento.
= Título do Documento
John Doe <john@go.com>; Jane Doe<jane@yo.com>; Black Beard <beardy@pirate.com>

Início do documento com múltiplos autores.
= Documento V1
Potato Man <chip@crunchy.com>
v1.0, 2016-01-13

Este artigo sobre batatas será divertido.
Você não precisa fazer nada especial para criar um parágrafo.

Adicione uma linha em branco entre os parágrafos para separá-los.

Para criar uma linha em branco adicione um +
e você terá uma quebra de linha!
_underscore é itálico_
*asterisco é negrito*
*_você pode combinar efeitos_*
`use crase para fonte monoespaçada`
`*fonte monoespaçada em negrito*`
= Nível 0 (Use apenas no cabeçalho do documento)

== Nível 1 <h2>

=== Nível 2 <h3>

==== Nível 3 <h4>

===== Nível 4 <h5>
* foo
* bar
* baz
. item 1
. item 2
. item 3
* foo 1
** foo 2
*** foo 3
**** foo 4
***** foo 5

. foo 1
.. foo 2
... foo 3
.... foo 4
..... foo 5
