
= Titolo documento

Prima frase del documento.

= Titolo documento
Primo Ultimo <first.last@learnxinyminutes.com>

Inizio del documento

= Titolo Documento
John Doe <john@go.com>; Jane Doe<jane@yo.com>; Black Beard <beardy@pirate.com>

Inizio di un documento con autori multipli.

= Titolo documento V1
Potato Man <chip@crunchy.com>
v1.0, 2016-01-13

Questo articolo sulle patatine sarà divertente.

Non hai bisogno di nulla di speciale per i paragrafi.

Aggiungi una riga vuota tra i paragrafi per separarli.

Per creare una riga vuota aggiungi un +
e riceverai una interruzione di linea!

_underscore crea corsivo_
*asterischi per il grassetto*
*_combinali per maggiore divertimento_*
`usa i ticks per indicare il monospazio`
`*spaziatura fissa in grassetto*`

= Livello 0 (può essere utilizzato solo nell'intestazione del documento)

== Livello 1 <h2>

=== Livello 2 <h3>

==== Livello 3 <h4>

===== Livello 4 <h5>

* foo
* bar
* baz

. item 1
. item 2
. item 3

* foo 1
** foo 2
*** foo 3
**** foo 4
***** foo 5

. foo 1
.. foo 2
... foo 3
.... foo 4
..... foo 5

