
= Judul Dokumen

Kalimat pertama dokumen.

= Judul Dokumen
Pertama terakhir <first.last@learnxinyminutes.com>

Awal dokumen ini.

= Judul Dokumen
John Doe <john@go.com>; Jane Doe <jane@yo.com>; Black Beard <beardy@pirate.com>

Memulai dokumen dengan banyak penulis.

= Judul Dokumen V1
Manusia Kentang <keripik@renyah.com>
v1.0, 2016/01/13

Artikel tentang keripik ini akan menjadi menyenangkan.

Anda tidak perlu sesuatu yang istimewa untuk paragraf.

Tambahkan baris kosong antara paragraf untuk memisahkan mereka.

Untuk membuat baris kosong, tambahkan: +
dan Anda akan mendapat satu baris kosong!

_underscore menciptakan miring_
*Tanda bintang untuk tebal*
*_Gabungkan biar makin asyik_*
`Penggunaan tanda petik untuk menandakan monospace`
`*Monospace tebal*`

= Level 0 (hanya dapat digunakan dalam header dokumen)

== Level 1 <h2>

=== Level 2 <h3>

==== Level 3 <h4>

===== Level 4 <h5>

* foo
* bar
* baz

. Item 1
. item 2
. Item 3

* Foo 1
** Foo 2
*** Foo 3
**** Foo 4
***** Foo 5

. foo 1
.. Foo 2
... Foo 3
.... Foo 4
..... Foo 5

