= Dokumententitel

Erster Satz des Dokuments.
= Dokumententitel
Vorname Nachname <Vorname.Nachname@learnxinyminutes.com>

Start des Dokuments.
= Dokumententitel
John Doe <john@go.com>; Jane Doe<jane@yo.com>; Black Beard <beardy@pirate.com>

Starte ein Dokument mit mehreren Autoren.
= Dokumententitel V1
Potato Man <chip@crunchy.com>
v1.0, 2016-01-13

Dieser Artikel über Chips wird Spaß machen.
Du musst nichts Besonderes machen für Absätze.

Füge eine Leerzeile zwischen zwei Absätze, um sie zu trennen.

Um eine Leerzeile zu erhalten musst du ein +
ergänzen und du erhältst einen Umbruch!
_Unterstriche erstellt Kursivschrift_
*Sternchen für Fett gedruckt*
*_Kombinieren für extra Spaß_*
`Benutze Ticks um Monospace zu signalisieren`
`*Fett gedruckter Monospace*`
= Level 0 (sollte nur in der Kopfzeile verwendet werden)

== Level 1 <h2>

=== Level 2 <h3>

==== Level 3 <h4>

===== Level 4 <h5>
* foo
* bar
* baz
. item 1
. item 2
. item 3
* foo 1
** foo 2
*** foo 3
**** foo 4
***** foo 5

. foo 1
.. foo 2
... foo 3
.... foo 4
..... foo 5
