= Título de documento

Primer contenido del documento.
= Título del documento
Nombre Apellido(s) <nombre.apellido@learnxinyminutes.com>

Inicio de este documento.
= Título del documento
John Doe <john@go.com>; Jane Doe<jane@yo.com>; Black Beard <beardy@pirate.com>

Inicio de un documento con múltiples autores.
= Título del documento V1
Potato Man <chip@crunchy.com>
v1.0, 2016-01-13

Este artículo sobre patatas fritas será genial.
No necesitas nada especial para un párrafo.

Inserta una línea vacía entre cada párrafo para separarlos.

Para insertar un salto de línea, solo añade un +
y ya lo tienes!
_guión bajo para cursiva_
*asteriscos para negrita*
*_combínalos y verás_*
`usa comillas invertidas para monospace`
`*combina para negrita monospace*`
= Nivel 0 (úsalo solo para el título del documento)

== Nivel 1 <h2>

=== Nivel 2 <h3>

==== Nivel 3 <h4>

===== Nivel 4 <h5>
* foo
* bar
* baz
. item 1
. item 2
. item 3
* foo 1
** foo 2
*** foo 3
**** foo 4
***** foo 5

. foo 1
.. foo 2
... foo 3
.... foo 4
..... foo 5
